name: Artifact Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Gradle
      run: |
        gradle help --scan
        ./gradlew assemblePrereleaseDebug

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: pull-request-build
        path: "app/build/outputs/apk/prerelease/debug/*.apk"

    - name: Deploy Problems Report to GH Pages
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        TARGET_DIR=gh-pages/$BRANCH_NAME
        mkdir -p $TARGET_DIR
        cp -r build/reports/problems/* $TARGET_DIR/
      shell: bash

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        user_name: "github-actions"
        user_email: "github-actions@github.com"
        commit_message: "Update problems report for ${{ github.ref_name }} [ci skip]"
